using System;
using System.Collections.Generic;

namespace Assets.Scripts
{
    public class LevelData
    {
        public string Code { get; set; }
        public string Goals { get; set; }
        public int Energy { get; set; }
        public int Lives { get; set; }
    }

    public class LevelMaster
    {
        public const int LevelCount = 31;
        public const int StepsPerLevel = 5;

        public LevelData GetLevel(int level, int step)
        {
            if (level < 0 || level >= LevelCount)
                throw new ArgumentOutOfRangeException(nameof(level));
            if (step < 0 || step >= StepsPerLevel)
                throw new ArgumentOutOfRangeException(nameof(step));

            var result = datas[(level * StepsPerLevel) + step];
            return L(result.Code.Replace("\r", ""), result.Goals.Replace("\r", ""), result.Energy);
        }

        private static LevelData L(string code, string goals, int energy, int lives = 3) => new()
        {
            Code = code,
            Goals = goals,
            Energy = energy,
            Lives = lives
        };

        private readonly List<LevelData> datas = new()
        {
            // Level 0 - SET / WAIT
            L(@"LET A AS 2
A IS 3
A IS 4", @"A == 4", 0),
            L(@"LET A AS 2
WAIT", @"A == 9", 12),
            L(@"LET B AS 3
LET C AS 7
WAIT
WAIT", @"B == 10
C != 7", 4),
            L(@"LET C AS 4
LET D AS 7
WAIT
C IS C + 1
WAIT
C IS C + 1
WAIT", @"C == 11
D < C", 4),
            L(@"LET CORE AS 6
LET SIDE AS 11
WAIT
CORE IS CORE + 1
WAIT
CORE IS CORE + 1
WAIT
CORE IS CORE + 1
WAIT
CORE IS CORE + 1
WAIT
CORE IS CORE + 1", @"CORE == 13
SIDE <= 10", 23, 1),

            // Level 1 - LET snapshots
            L(@"LET BASE AS 5
BASE IS BASE + 1
WAIT", @"COPY == 5
BASE >= 5", 23),
            L(@"LET SEED AS 6
SEED IS SEED + 1
WAIT
LET D0 AS 0", @"SNAP == 6
SEED != 8
D0 < SNAP", 5),
            L(@"LET RATE AS 7
RATE IS RATE + 1
WAIT
LET D0 AS 1
D0 IS D0 + 1
LET D1 AS 2
D0 IS D0 + 2", @"GAIN == 7
RATE > D0
D1 <= 1
D0 != 4", 0),
            L(@"LET LIM AS 8
LIM IS LIM + 1
WAIT
WAIT
WAIT
LET D0 AS 2
LET D3 AS 5
D3 IS D3 + 1", @"SAVE == 8
D0 == 5
D3 < D0", 10),
            L(@"LET MODE AS 9
MODE IS MODE + 1
WAIT
LET D0 AS 3
D0 IS D0 + 2
LET D1 AS 4
D0 IS D0 + 2", @"MARK == 9
MODE == 9
D0 != 7
D1 > MODE", 13, 1),

            // Level 2 - LET expressions
            L(@"LET A AS 6
LET B AS 8
A IS A + 1
WAIT", @"SUM == 14
A != 8
B < SUM", 24),
            L(@"LET X AS 7
LET Y AS 9
X IS X + 1
WAIT
LET D0 AS 7", @"X > D0
Y > DIFF
D0 <= 8", 0),
            L(@"LET BASE AS 8
LET RATE AS 10
BASE IS BASE + 1
WAIT
LET D0 AS 8", @"PROD == 80
BASE > D0
RATE >= 9
D0 != 8", 10),
            L(@"LET WIDE AS 9
LET TALL AS 11
WIDE IS WIDE + 1
WAIT
TEMP IS TEMP - 1", @"AREA == 99
TALL < 11
WIDE >= 11", 2, 1),
            L(@"LET LEFT AS 10
RITE IS 12
LEFT IS LEFT + 1
WAIT
D0 IS 1
D1 IS D0 + 1
D2 IS D1 + 1
D3 IS D2 + 1", @"SPAN == -2", 24),

            // Level 3 - LOOP basics
            L(@"LET CNT AS 0
LOOP CNT < 10
   CNT IS CNT + 1
WAIT", @"CNT == 10", 0, 3),
            L(@"LET CNT AS 0
LOOP CNT < 10
   CNT IS CNT + 1
WAIT", @"CNT == 9", 18, 4),
            L(@"LET RATE AS 2
LIM IS 10
LOOP CNT < LIM
   CNT IS CNT + 1
   SUM IS SUM + RATE
WAIT", @"RATE == 3
SUM == 30
CNT == 10", 10),
            L(@"LET CNT AS 6
LET USED AS 0
LOOP CNT > 0
   CNT IS CNT - 1
   USED IS USED + 1
WAIT", @"USED == 9
CNT == 9000", 5),
            L(@"LET WIDE AS 4
LET HIGH AS 3
LET X AS 0
LET Y AS 0
LOOP X < WIDE
   LOOP Y < HIGH
      Y IS Y + 1
      X IS X + 1
WAIT", @"X >= 3
Y != 4
HIGH <= WIDE", 15, 2),

            // Level 4 - LOOP accumulators
            L(@"LET LIM AS 4
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   SUM IS SUM + I
WAIT", @"LIM == 5
I <= 5
SUM != 16", 12, 4),
            L(@"LET LIM AS 4
LET I AS 0
LET PROD AS 2
WAIT
WAIT
WAIT
WAIT
WAIT
LOOP I < LIM
   I IS I + 1
   PROD IS PROD * PROD", @"PROD == 16", 10),
            L(@"LET A AS 8
LET B AS 1
WAIT
WAIT
WAIT
LOOP A != B
   A IS A + 1
   B IS B - 1
WAIT
WAIT", @"A == B", 5),
            L(@"LET X AS 10
LET Y AS 0
LET Z AS 0
LOOP X > Y
   Y IS X - Y
   LOOP Y > Z
      Z IS Y - Z
      Y IS X - Z
   X IS X + 1
WAIT", @"Y < 3
X != Y", 10),
            L(@"LET Y AS 0
LET Z AS 0
LOOP X > 0
   LOOP Y < X
      Y IS Y + 1
      Z IS Z - 1
   X IS X - 1", @"X > 10
Y == 10
Z != 10
| 35 |", 13, 2),

            // Level 5 - STOP basics
            L(@"LET ADD AS 2
LET CNT AS 0
LET SUM AS 0
LOOP CNT < 5
   CNT IS CNT + 1
   SUM IS SUM + ADD
   STOP
WAIT", @"ADD == 5
SUM != 6
CNT < ADD", 22),
            L(@"LET BASE AS 4
LET CNT AS 0
LET OUT AS 0
LOOP CNT < 8
   CNT IS CNT + 1
   OUT IS BASE * CNT
   STOP
OUT IS OUT + BASE
WAIT", @"BASE == 6
OUT > BASE
CNT >= 1", 10),
            L(@"LET STEP AS 2
LET CNT AS 9
LET USED AS 0
LOOP CNT > 0
   CNT IS CNT - STEP
   USED IS USED + 1
   STOP
CNT IS CNT - STEP
WAIT", @"STEP == 3
CNT >= 3
USED <= 1", 10),
            L(@"LET WIDE AS 3
LET HIGH AS 4
LET X AS 0
LET Y AS 0
LET CELL AS 0
LOOP X < WIDE
   Y IS 0
   LOOP Y < HIGH
      CELL IS CELL + 1
      Y IS Y + 1
      STOP
   X IS X + 1
WAIT", @"WIDE == 4
X <= 4
CELL != 5
Y < WIDE
HIGH <= CELL", 10, 1),
            L(@"LET WIDE AS 3
LET HIGH AS 5
LET X AS 0
LET Y AS 0
LET SUM AS 0
LET RATE AS 2
LOOP X < WIDE
   Y IS 0
   LOOP Y < HIGH
      SUM IS SUM + RATE
      Y IS Y + 1
      STOP
   SUM IS SUM + X
   X IS X + 1
WAIT", @"RATE == 4
SUM != 16
X < RATE
Y >= 1
HIGH > Y
WIDE != 4", 50, 2),

            // Level 6 - STOP reinforcement
            L(@"LET RATE AS 3
LET CNT AS 0
LET SUM AS 1
LOOP CNT < 9
   CNT IS CNT + 1
   SUM IS SUM * RATE
   STOP
SUM IS SUM + CNT
WAIT", @"RATE == 4
SUM > RATE
CNT >= 1", 22),
            L(@"LET ADD AS 2
LET CNT AS 0
LET SUM AS 0
LOOP CNT < 9
   CNT IS CNT + 1
   SUM IS SUM + ADD
   SUM IS SUM + CNT
   STOP
WAIT", @"ADD == 5
SUM >= 6
CNT <= 1", 10),
            L(@"LET LIM AS 7
LET CNT AS 0
LET SUM AS 0
LOOP CNT < LIM
   CNT IS CNT + 2
   SUM IS SUM + CNT
   STOP
SUM IS SUM + LIM
WAIT", @"LIM == 9
SUM <= 11
CNT != 3", 0),
            L(@"LET WIDE AS 3
LET HIGH AS 4
LET X AS 0
LET Y AS 0
LET SUM AS 0
LOOP X < WIDE
   Y IS 0
   LOOP Y < HIGH
      Y IS Y + 1
      SUM IS SUM + Y
      STOP
   SUM IS SUM + X
   X IS X + 1
WAIT", @"WIDE == 4
X != 5
SUM > WIDE
Y >= 1
HIGH > Y", 10),
            L(@"LET WIDE AS 4
LET HIGH AS 6
LET X AS 0
LET Y AS 0
LET SUM AS 0
LET ADD AS 1
LOOP X < WIDE
   Y IS 0
   LOOP Y < HIGH
      Y IS Y + 1
      SUM IS SUM + ADD
      STOP
   SUM IS SUM + X
   X IS X + 1
SUM IS SUM + HIGH
WAIT", @"ADD == 3
SUM > ADD
X >= 4
Y <= 1
HIGH >= 5
WIDE < SUM", 37, 1),

            // Level 7 - SKIP reading
            L(@"LET LIM AS 3
LET CNT AS 0
LET SUM AS 0
LOOP CNT < LIM
   CNT IS CNT + 1
   SUM IS SUM + CNT
   SKIP
   SUM IS 99
WAIT", @"LIM == 4
CNT >= 4
SUM <= 10", 12),
            L(@"LET RATE AS 2
LET LIM AS 4
LET CNT AS 0
LET SUM AS 0
LOOP CNT < LIM
   CNT IS CNT + 1
   SUM IS SUM + RATE
   SKIP
   RATE IS 99
WAIT", @"RATE == 3
SUM <= 12
CNT != 5
LIM < SUM", 0),
            L(@"LET STEP AS 2
LET CNT AS 0
LET SUM AS 0
LOOP CNT < 6
   CNT IS CNT + STEP
   SUM IS SUM + CNT
   SKIP
   SUM IS 0
SUM IS SUM + STEP
WAIT", @"STEP == 3
SUM != 13
CNT > STEP", 0),
            L(@"LET WIDE AS 3
LET HIGH AS 2
LET X AS 0
LET Y AS 0
LET SUM AS 0
LOOP X < WIDE
   Y IS 0
   LOOP Y < HIGH
      Y IS Y + 1
      SUM IS SUM + Y
      SKIP
      SUM IS 99
   X IS X + 1
WAIT", @"HIGH == 3
Y >= HIGH
SUM >= 18
X <= 3
WIDE != 4", 0),
            L(@"LET WIDE AS 3
LET HIGH AS 3
LET X AS 0
LET Y AS 0
LET SUM AS 0
LET ADD AS 1
LOOP X < WIDE
   Y IS 0
   LOOP Y < HIGH
      Y IS Y + 1
      SUM IS SUM + ADD
      SKIP
      ADD IS 20
   SUM IS SUM + X
   X IS X + 1
WAIT", @"ADD == 2
SUM >= 21
X <= 3
Y != 4
HIGH != 4
WIDE < SUM", 17, 1),

            // Level 8 - IF / ELSE
            L(@"LET CUT AS 8
LET CNT AS 0
LET SUM AS 0
LOOP CNT < 3
   CNT IS CNT + 1
   SUM IS SUM + CNT
IF SUM >= CUT
   SUM IS SUM + 1
ELSE
   SUM IS SUM - 1
WAIT", @"CUT == 6
SUM <= 7
CNT != 4", 12),
            L(@"LET RATE AS 2
LET LIM AS 4
LET CNT AS 0
LET SUM AS 0
LET FLAG AS 0
LOOP CNT < LIM
   CNT IS CNT + 1
   SUM IS SUM + RATE
IF SUM > LIM
   FLAG IS SUM
ELSE
   FLAG IS LIM
WAIT", @"RATE == 1
SUM != 5
FLAG > RATE
CNT <= LIM
LIM >= 3", 0),
            L(@"LET CUT AS 5
LET CNT AS 6
LET USED AS 0
LET FLAG AS 0
LOOP CNT > 0
   CNT IS CNT - 2
   USED IS USED + 1
IF USED == CUT
   FLAG IS 1
ELSE
   FLAG IS USED
WAIT", @"CUT == 3
FLAG < CUT
USED >= 3
CNT <= 1", 0),
            L(@"LET CUT AS 10
LET WIDE AS 3
LET HIGH AS 2
LET X AS 0
LET Y AS 0
LET CELL AS 0
LET FLAG AS 0
LOOP X < WIDE
   Y IS 0
   LOOP Y < HIGH
      CELL IS CELL + 1
      Y IS Y + 1
   X IS X + 1
IF CELL >= CUT
   FLAG IS 1
ELSE
   FLAG IS CELL
WAIT", @"CUT == 6
FLAG >= 1
CELL <= 6
HIGH < CELL
WIDE <= 4
X >= 2
Y != 3", 0),
            L(@"LET CUT AS 12
LET WIDE AS 3
LET HIGH AS 3
LET X AS 0
LET Y AS 0
LET SUM AS 0
LET FLAG AS 0
LOOP X < WIDE
   Y IS 0
   LOOP Y < HIGH
      SUM IS SUM + X
      Y IS Y + 1
   X IS X + 1
IF SUM != CUT
   FLAG IS SUM
ELSE
   FLAG IS -1
SUM IS SUM + FLAG
WAIT", @"CUT == 9
SUM <= 8
FLAG != 0
HIGH < CUT
WIDE >= 2
X != 4
Y <= WIDE", 12, 2),

            // Level 9 - conditions in LOOP
            L(@"LET CUT AS 2
LET LIM AS 4
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I > CUT
      SUM IS SUM + I
   ELSE
      SUM IS SUM + CUT
WAIT", @"CUT == 1
SUM != 11
I > CUT
LIM >= 3", 12),
            L(@"LET MOD AS 2
LET LIM AS 5
LET I AS 0
LET REM AS 0
LET HIT AS 0
LET MISS AS 0
LOOP I < LIM
   I IS I + 1
   REM IS I % MOD
   IF REM == 0
      HIT IS HIT + 1
   ELSE
      MISS IS MISS + 1
WAIT", @"MOD == 3
HIT < MOD
MISS >= 4
I <= 5
LIM != 6", 0),
            L(@"LET CUT AS 4
LET LIM AS 6
LET I AS 0
LET LOW AS 0
LET HIGH AS 0
LOOP I < LIM
   I IS I + 1
   IF I <= CUT
      LOW IS LOW + I
   ELSE
      HIGH IS HIGH + I
WAIT", @"CUT == 3
LOW >= 6
HIGH <= 15
I != 7
LIM < HIGH", 0),
            L(@"LET CUT AS 3
LET WIDE AS 4
LET HIGH AS 2
LET X AS 0
LET Y AS 0
LET SUM AS 0
LOOP X < WIDE
   Y IS 0
   LOOP Y < HIGH
      Y IS Y + 1
      IF X < CUT
         SUM IS SUM + Y
      ELSE
         SUM IS SUM + X
   X IS X + 1
WAIT", @"CUT == 2
SUM <= 16
X != 5
Y >= CUT
HIGH <= Y
WIDE <= 5", 0),
            L(@"LET CUT AS 2
LET WIDE AS 3
LET HIGH AS 3
LET X AS 0
LET Y AS 0
LET SUM AS 0
LET CNT AS 0
LOOP X < WIDE
   Y IS 0
   LOOP Y < HIGH
      Y IS Y + 1
      IF Y > CUT
         SUM IS SUM + X
      ELSE
         SUM IS SUM + Y
      CNT IS CNT + 1
   X IS X + 1
WAIT", @"CUT == 1
SUM != 10
X > CUT
Y >= 3
CNT <= 9
HIGH <= 4
WIDE != 4", 12, 2),

            // Level 10 - compound conditions
            L(@"LET LOW AS 2
LET HIGH AS 4
LET LIM AS 5
LET I AS 0
LET HIT AS 0
LOOP I < LIM
   I IS I + 1
   IF I >= LOW AND I <= HIGH
      HIT IS HIT + I
   ELSE
      HIT IS HIT + 0
WAIT", @"LOW == 1
HIT > LOW
I >= 5
HIGH <= 5", 12),
            L(@"LET MOD AS 2
LET CUT AS 3
LET LIM AS 6
LET I AS 0
LET REM AS 0
LET HIT AS 0
LOOP I < LIM
   I IS I + 1
   REM IS I % MOD
   IF REM == 0 AND I > CUT
      HIT IS HIT + 1
   ELSE
      HIT IS HIT + 0
WAIT", @"CUT == 1
HIT >= 3
I <= 6
LIM > REM
MOD <= 3", 0),
            L(@"LET LOW AS 2
LET HIGH AS 5
LET LIM AS 7
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < LOW OR I > HIGH
      SUM IS SUM + I
   ELSE
      SUM IS SUM + LOW
WAIT", @"HIGH == 4
SUM <= 25
I != 8
LIM > HIGH
LOW <= 3", 0),
            L(@"LET LOW AS 1
LET HIGH AS 3
LET WIDE AS 4
LET YMAX AS 3
LET X AS 0
LET Y AS 0
LET HIT AS 0
LOOP X < WIDE
   Y IS 0
   LOOP Y < YMAX
      Y IS Y + 1
      IF X >= LOW AND Y <= HIGH
         HIT IS HIT + 1
      ELSE
         HIT IS HIT + 0
   X IS X + 1
WAIT", @"LOW == 2
HIT != 7
X > LOW
Y >= 3
HIGH < X
WIDE >= 3
YMAX < WIDE", 0),
            L(@"LET LOW AS 1
LET HIGH AS 3
LET WIDE AS 4
LET YMAX AS 3
LET X AS 0
LET Y AS 0
LET SUM AS 0
LET HIT AS 0
LOOP X < WIDE
   Y IS 0
   LOOP Y < YMAX
      Y IS Y + 1
      IF X >= LOW AND Y <= HIGH
         SUM IS SUM + X
         HIT IS HIT + 1
      ELSE
         SUM IS SUM + Y
   X IS X + 1
WAIT", @"HIGH == 2
SUM > HIGH
HIT >= 6
X <= 4
Y != 4
LOW >= 0
WIDE < HIT
YMAX >= 2", 13, 1),

            // Level 11 - ELIF / LIST
            L(@"LET HIGH AS 3
LIST BUF
LET I AS 0
LET A AS 0
LET B AS 0
LOOP I < 3
   I IS I + 1
   IF I < 2
      A IS A + 1
   ELIF I <= HIGH
      B IS B + 1
   ELSE
      B IS B + 2
WAIT", @"HIGH == 4
I >= 3
A <= 1
B != 3
LENGTH:BUF >= 0", 12),
            L(@"LET HIGH AS 4
LET LIM AS 4
LIST BUF
LET I AS 0
LET A AS 0
LET B AS 0
LET C AS 0
LOOP I < LIM
   I IS I + 1
   IF I < 2
      A IS A + 1
   ELIF I <= HIGH
      B IS B + 1
   ELSE
      C IS C + 1
WAIT", @"HIGH == 5
I <= 4
A != 2
B < HIGH
C >= 0
LENGTH:BUF == 0", 0),
            L(@"LET HIGH AS 3
LET LIM AS 5
LIST BUF
LET I AS 0
LET A AS 0
LET B AS 0
LET C AS 0
LOOP I < LIM
   I IS I + 1
   IF I < 2
      A IS A + 1
   ELIF I <= HIGH
      B IS B + 1
   ELSE
      C IS C + 1
B IS B + LENGTH:BUF
WAIT", @"HIGH == 4
B != 4
C < HIGH
I >= 5
A <= 1
LENGTH:BUF >= 0", 0),
            L(@"LET HIGH AS 4
LET LIM AS 3
LIST BUF
LET I AS 0
LET A AS 0
LET B AS 0
LET C AS 0
LOOP I < LIM
   I IS I + 1
   IF I < 2
      A IS A + 1
   ELIF I <= HIGH
      B IS B + 1
   ELSE
      C IS C + 1
B IS B + LENGTH:BUF
WAIT", @"HIGH == 5
I < HIGH
A >= 1
B <= 2
C != 1
LENGTH:BUF == 0
LIM < HIGH", 0),
            L(@"LET HIGH AS 3
LET LIM AS 4
LIST BUF
LET I AS 0
LET A AS 0
LET B AS 0
LET C AS 0
LOOP I < LIM
   I IS I + 1
   IF I < 2
      A IS A + 1
   ELIF I <= HIGH
      B IS B + 1
   ELSE
      C IS C + 1
B IS B + LENGTH:BUF
WAIT", @"HIGH == 4
B >= 3
C <= 0
I != 5
A < HIGH
LENGTH:BUF >= 0
LIM <= 5", 12, 1),

            // Level 12 - FIRST / LAST
            L(@"LET HIGH AS 3
LIST BUF
LET I AS 0
LET A AS 0
LET B AS 0
LOOP I < 3
   I IS I + 1
   IF I < 2
      A IS A + 1
   ELIF I <= HIGH
      B IS B + 1
   ELSE
      B IS B + 2
   B IS B + LENGTH:BUF
WAIT", @"HIGH == 4
I <= 3
A != 2
B < HIGH
LENGTH:BUF == 0", 12),
            L(@"LET HIGH AS 4
LET LIM AS 4
LIST BUF
LET I AS 0
LET A AS 0
LET B AS 0
LET C AS 0
LOOP I < LIM
   I IS I + 1
   IF I < 2
      A IS A + 1
   ELIF I <= HIGH
      B IS B + 1
   ELSE
      C IS C + 1
   B IS B + LENGTH:BUF
WAIT", @"HIGH == 5
I != 5
A < HIGH
B >= 3
C <= 0
LENGTH:BUF >= 0", 0),
            L(@"LET HIGH AS 3
LET LIM AS 5
LIST BUF
LET I AS 0
LET A AS 0
LET B AS 0
LET C AS 0
LOOP I < LIM
   I IS I + 1
   IF I < 2
      A IS A + 1
   ELIF I <= HIGH
      B IS B + 1
   ELSE
      C IS C + 1
   B IS B + LENGTH:BUF
WAIT", @"HIGH == 4
B < HIGH
C >= 1
I <= 5
A != 2
LENGTH:BUF == 0", 0),
            L(@"LET HIGH AS 4
LET LIM AS 3
LIST BUF
LET I AS 0
LET A AS 0
LET B AS 0
LET C AS 0
LOOP I < LIM
   I IS I + 1
   IF I < 2
      A IS A + 1
   ELIF I <= HIGH
      B IS B + 1
   ELSE
      C IS C + 1
   B IS B + LENGTH:BUF
WAIT", @"HIGH == 5
I >= 3
A <= 1
B != 3
C < HIGH
LENGTH:BUF >= 0
LIM <= 4", 0),
            L(@"LET HIGH AS 3
LET LIM AS 4
LIST BUF
LET I AS 0
LET A AS 0
LET B AS 0
LET C AS 0
LOOP I < LIM
   I IS I + 1
   IF I < 2
      A IS A + 1
   ELIF I <= HIGH
      B IS B + 1
   ELSE
      C IS C + 1
   B IS B + LENGTH:BUF
WAIT", @"HIGH == 4
B <= 3
C != 1
I >= HIGH
A >= 1
LENGTH:BUF == 0
LIM >= 3", 12, 1),

            // Level 13 - list reading
            L(@"LET HIGH AS 3
LIST BUF
LET I AS 0
LET A AS 0
LET B AS 0
LOOP I < 3
   I IS I + 1
   IF I < 2
      A IS A + 1
   ELIF I <= HIGH
      B IS B + 1
   ELSE
      B IS B + 2
   B IS B + LENGTH:BUF
LIST AUX
B IS B + LENGTH:AUX", @"HIGH == 4
I != 4
A < HIGH
B >= 2
LENGTH:BUF >= 0
LENGTH:AUX == 0", 12),
            L(@"LET HIGH AS 4
LET LIM AS 4
LIST BUF
LET I AS 0
LET A AS 0
LET B AS 0
LET C AS 0
LOOP I < LIM
   I IS I + 1
   IF I < 2
      A IS A + 1
   ELIF I <= HIGH
      B IS B + 1
   ELSE
      C IS C + 1
   B IS B + LENGTH:BUF
LIST AUX
B IS B + LENGTH:AUX", @"HIGH == 5
I < HIGH
A >= 1
B <= 3
C != 1
LENGTH:BUF == 0
LENGTH:AUX >= 0", 0),
            L(@"LET HIGH AS 3
LET LIM AS 5
LIST BUF
LET I AS 0
LET A AS 0
LET B AS 0
LET C AS 0
LOOP I < LIM
   I IS I + 1
   IF I < 2
      A IS A + 1
   ELIF I <= HIGH
      B IS B + 1
   ELSE
      C IS C + 1
   B IS B + LENGTH:BUF
LIST AUX
B IS B + LENGTH:AUX
WAIT", @"HIGH == 4
B >= 3
C <= 1
I != 6
A < HIGH
LENGTH:BUF >= 0
LENGTH:AUX == 0", 0),
            L(@"LET HIGH AS 4
LET LIM AS 3
LIST BUF
LET I AS 0
LET A AS 0
LET B AS 0
LET C AS 0
LOOP I < LIM
   I IS I + 1
   IF I < 2
      A IS A + 1
   ELIF I <= HIGH
      B IS B + 1
   ELSE
      C IS C + 1
   B IS B + LENGTH:BUF
LIST AUX
B IS B + LENGTH:AUX
WAIT", @"HIGH == 5
I <= 3
A != 2
B < HIGH
C >= 0
LENGTH:BUF == 0
LENGTH:AUX >= 0", 0),
            L(@"LET HIGH AS 3
LET LIM AS 4
LIST BUF
LET I AS 0
LET A AS 0
LET B AS 0
LET C AS 0
LOOP I < LIM
   I IS I + 1
   IF I < 2
      A IS A + 1
   ELIF I <= HIGH
      B IS B + 1
   ELSE
      C IS C + 1
   B IS B + LENGTH:BUF
LIST AUX
B IS B + LENGTH:AUX
WAIT", @"HIGH == 4
B != 4
C < HIGH
I >= 4
A <= 1
LENGTH:BUF >= 0
LENGTH:AUX == 0
LIM != 5", 12, 1),

            // Level 14 - PUSH basics
            L(@"LET LOW AS 2
LET HIGH AS 4
LET LIM AS 4
LIST OUT
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < LOW
      PUSH OUT IS LOW
      SUM IS SUM + LOW
   ELIF I <= HIGH
      PUSH OUT IS I
      SUM IS SUM + I
   ELSE
      PUSH OUT IS HIGH
      SUM IS SUM + HIGH", @"HIGH == 5
LOW < HIGH
I >= 4
SUM <= 11
OUT == [2,2,3,4]
LENGTH:OUT == 4", 13),
            L(@"LET LOW AS 3
LET HIGH AS 5
LET LIM AS 5
LIST OUT
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < LOW
      PUSH OUT IS LOW
      SUM IS SUM + LOW
   ELIF I <= HIGH
      PUSH OUT IS I
      SUM IS SUM + I
   ELSE
      PUSH OUT IS HIGH
      SUM IS SUM + HIGH
WAIT", @"LOW == 2
SUM >= 16
HIGH <= 5
I != 6
OUT == [2,2,3,4,5]
LENGTH:OUT >= 4", 0),
            L(@"LET LOW AS 2
LET HIGH AS 4
LET LIM AS 6
LIST OUT
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < LOW
      PUSH OUT IS LOW
      SUM IS SUM + LOW
   ELIF I <= HIGH
      PUSH OUT IS I
      SUM IS SUM + I
   ELSE
      PUSH OUT IS HIGH
      SUM IS SUM + HIGH
WAIT", @"HIGH == 5
SUM <= 21
LOW != 3
I > HIGH
OUT == [2,2,3,4,5,5]
LENGTH:OUT == 6
LIM > HIGH", 0),
            L(@"LET LOW AS 3
LET HIGH AS 5
LET LIM AS 4
LIST OUT
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < LOW
      PUSH OUT IS LOW
      SUM IS SUM + LOW
   ELIF I <= HIGH
      PUSH OUT IS I
      SUM IS SUM + I
   ELSE
      PUSH OUT IS HIGH
      SUM IS SUM + HIGH
WAIT", @"LOW == 2
SUM != 12
HIGH > LOW
I >= 4
OUT == [2,2,3,4]
LENGTH:OUT >= 3
LIM <= I", 0),
            L(@"LET LOW AS 2
LET HIGH AS 4
LET LIM AS 5
LIST OUT
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < LOW
      PUSH OUT IS LOW
      SUM IS SUM + LOW
   ELIF I <= HIGH
      PUSH OUT IS I
      SUM IS SUM + I
   ELSE
      PUSH OUT IS HIGH
      SUM IS SUM + HIGH
WAIT", @"HIGH == 5
SUM > HIGH
LOW >= 2
I <= 5
OUT == [2,2,3,4,5]
LENGTH:OUT == 5
LIM <= 6", 13, 1),

            // Level 15 - PUSH filtering
            L(@"LET LOW AS 2
LET HIGH AS 4
LET LIM AS 4
LIST OUT
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < LOW
      PUSH OUT IS LOW
      SUM IS SUM + LOW
   ELIF I <= HIGH
      PUSH OUT IS I
      SUM IS SUM + I
   ELSE
      PUSH OUT IS HIGH
      SUM IS SUM + HIGH", @"HIGH == 5
LOW >= 2
I <= 4
SUM != 12
OUT == [2,2,3,4]
LENGTH:OUT >= 3", 13),
            L(@"LET LOW AS 3
LET HIGH AS 5
LET LIM AS 5
LIST OUT
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < LOW
      PUSH OUT IS LOW
      SUM IS SUM + LOW
   ELIF I <= HIGH
      PUSH OUT IS I
      SUM IS SUM + I
   ELSE
      PUSH OUT IS HIGH
      SUM IS SUM + HIGH
WAIT", @"LOW == 2
SUM <= 16
HIGH != 6
I > LOW
OUT == [2,2,3,4,5]
LENGTH:OUT == 5", 0),
            L(@"LET LOW AS 2
LET HIGH AS 4
LET LIM AS 6
LIST OUT
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < LOW
      PUSH OUT IS LOW
      SUM IS SUM + LOW
   ELIF I <= HIGH
      PUSH OUT IS I
      SUM IS SUM + I
   ELSE
      PUSH OUT IS HIGH
      SUM IS SUM + HIGH
WAIT", @"HIGH == 5
SUM != 22
LOW < HIGH
I >= 6
OUT == [2,2,3,4,5,5]
LENGTH:OUT >= 5
LIM > HIGH", 0),
            L(@"LET LOW AS 3
LET HIGH AS 5
LET LIM AS 4
LIST OUT
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < LOW
      PUSH OUT IS LOW
      SUM IS SUM + LOW
   ELIF I <= HIGH
      PUSH OUT IS I
      SUM IS SUM + I
   ELSE
      PUSH OUT IS HIGH
      SUM IS SUM + HIGH
WAIT", @"LOW == 2
SUM > LOW
HIGH >= 5
I <= 4
OUT == [2,2,3,4]
LENGTH:OUT == 4
LIM <= 5", 0),
            L(@"LET LOW AS 2
LET HIGH AS 4
LET LIM AS 5
LIST OUT
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < LOW
      PUSH OUT IS LOW
      SUM IS SUM + LOW
   ELIF I <= HIGH
      PUSH OUT IS I
      SUM IS SUM + I
   ELSE
      PUSH OUT IS HIGH
      SUM IS SUM + HIGH
WAIT", @"HIGH == 5
SUM >= 16
LOW <= 2
I != 6
OUT == [2,2,3,4,5]
LENGTH:OUT >= 4
LIM >= 4", 13, 1),

            // Level 16 - PUSH transforms
            L(@"LET LOW AS 2
LET HIGH AS 4
LET LIM AS 4
LIST OUT
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < LOW
      PUSH OUT IS LOW
      SUM IS SUM + LOW
   ELIF I <= HIGH
      PUSH OUT IS I
      SUM IS SUM + I
   ELSE
      PUSH OUT IS HIGH
      SUM IS SUM + HIGH
LET HEAD AS FIRST:OUT
SUM IS SUM + HEAD", @"HIGH == 5
LOW <= 2
I != 5
SUM > HIGH
HEAD >= 2
OUT == [2,2,3,4]
LENGTH:OUT == 4", 13),
            L(@"LET LOW AS 3
LET HIGH AS 5
LET LIM AS 5
LIST OUT
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < LOW
      PUSH OUT IS LOW
      SUM IS SUM + LOW
   ELIF I <= HIGH
      PUSH OUT IS I
      SUM IS SUM + I
   ELSE
      PUSH OUT IS HIGH
      SUM IS SUM + HIGH
LET HEAD AS FIRST:OUT
SUM IS SUM + HEAD
LET TAIL AS LAST:OUT
SUM IS SUM + TAIL", @"LOW == 2
SUM != 24
HEAD >= LOW
HIGH >= 5
I <= 5
TAIL != 6
OUT == [2,2,3,4,5]
LENGTH:OUT >= 4", 0),
            L(@"LET LOW AS 2
LET HIGH AS 4
LET LIM AS 6
LIST OUT
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < LOW
      PUSH OUT IS LOW
      SUM IS SUM + LOW
   ELIF I <= HIGH
      PUSH OUT IS I
      SUM IS SUM + I
   ELSE
      PUSH OUT IS HIGH
      SUM IS SUM + HIGH
LET HEAD AS FIRST:OUT
SUM IS SUM + HEAD
LET TAIL AS LAST:OUT
SUM IS SUM + TAIL", @"HIGH == 5
SUM > HIGH
TAIL >= 5
LOW <= 2
I != 7
HEAD < HIGH
OUT == [2,2,3,4,5,5]
LENGTH:OUT == 6", 0),
            L(@"LET LOW AS 3
LET HIGH AS 5
LET LIM AS 4
LIST OUT
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < LOW
      PUSH OUT IS LOW
      SUM IS SUM + LOW
   ELIF I <= HIGH
      PUSH OUT IS I
      SUM IS SUM + I
   ELSE
      PUSH OUT IS HIGH
      SUM IS SUM + HIGH
LET HEAD AS FIRST:OUT
SUM IS SUM + HEAD
LET TAIL AS LAST:OUT
SUM IS SUM + TAIL", @"LOW == 2
SUM >= 17
HEAD <= 2
HIGH != 6
I > LOW
TAIL >= 4
OUT == [2,2,3,4]
LENGTH:OUT >= 3", 0),
            L(@"LET LOW AS 2
LET HIGH AS 4
LET LIM AS 5
LIST OUT
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < LOW
      PUSH OUT IS LOW
      SUM IS SUM + LOW
   ELIF I <= HIGH
      PUSH OUT IS I
      SUM IS SUM + I
   ELSE
      PUSH OUT IS HIGH
      SUM IS SUM + HIGH
LET HEAD AS FIRST:OUT
SUM IS SUM + HEAD
LET TAIL AS LAST:OUT
SUM IS SUM + TAIL", @"HIGH == 5
SUM <= 23
TAIL != 6
LOW < HIGH
I >= 5
HEAD <= 2
OUT == [2,2,3,4,5]
LENGTH:OUT == 5
LIM <= HIGH", 13, 1),

            // Level 17 - INJECT basics
            L(@"LET CUT AS 2
LET LIM AS 4
LIST OUT
PUSH OUT IS 9
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < CUT
      INJECT OUT IS I
      SUM IS SUM + I
   ELIF I == CUT
      PUSH OUT IS I
      SUM IS SUM + CUT
   ELSE
      INJECT OUT IS CUT
      SUM IS SUM + CUT", @"CUT == 3
SUM != 10
I > CUT
OUT == [3,2,1,9,3]
LENGTH:OUT >= 4", 12),
            L(@"LET CUT AS 3
LET LIM AS 5
LIST OUT
PUSH OUT IS 9
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < CUT
      INJECT OUT IS I
      SUM IS SUM + I
   ELIF I == CUT
      PUSH OUT IS I
      SUM IS SUM + CUT
   ELSE
      INJECT OUT IS CUT
      SUM IS SUM + CUT", @"CUT == 4
SUM > CUT
I >= 5
OUT == [4,3,2,1,9,4]
LENGTH:OUT == 6
LIM <= 6", 0),
            L(@"LET CUT AS 2
LET LIM AS 6
LIST OUT
PUSH OUT IS 9
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < CUT
      INJECT OUT IS I
      SUM IS SUM + I
   ELIF I == CUT
      PUSH OUT IS I
      SUM IS SUM + CUT
   ELSE
      INJECT OUT IS CUT
      SUM IS SUM + CUT", @"CUT == 3
SUM >= 15
I <= 6
OUT == [3,3,3,2,1,9,3]
LENGTH:OUT >= 6
LIM >= 5", 0),
            L(@"LET CUT AS 3
LET LIM AS 4
LIST OUT
PUSH OUT IS 9
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < CUT
      INJECT OUT IS I
      SUM IS SUM + I
   ELIF I == CUT
      PUSH OUT IS I
      SUM IS SUM + CUT
   ELSE
      INJECT OUT IS CUT
      SUM IS SUM + CUT", @"CUT == 4
SUM <= 10
I != 5
OUT == [3,2,1,9,4]
LENGTH:OUT == 5
LIM != 5", 0),
            L(@"LET CUT AS 2
LET LIM AS 5
LIST OUT
PUSH OUT IS 9
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < CUT
      INJECT OUT IS I
      SUM IS SUM + I
   ELIF I == CUT
      PUSH OUT IS I
      SUM IS SUM + CUT
   ELSE
      INJECT OUT IS CUT
      SUM IS SUM + CUT", @"CUT == 3
SUM != 13
I > CUT
OUT == [3,3,2,1,9,3]
LENGTH:OUT >= 5
LIM > CUT", 12, 1),

            // Level 18 - deque operations
            L(@"LET CUT AS 2
LET LIM AS 4
LIST OUT
PUSH OUT IS 9
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < CUT
      INJECT OUT IS I
      SUM IS SUM + I
   ELIF I == CUT
      PUSH OUT IS I
      SUM IS SUM + CUT
   ELSE
      INJECT OUT IS CUT
      SUM IS SUM + CUT
LET HEAD AS FIRST:OUT
LET TAIL AS LAST:OUT
SUM IS SUM + HEAD
SUM IS SUM + TAIL", @"CUT == 3
SUM > CUT
HEAD >= 3
TAIL <= 3
I != 5
OUT == [3,2,1,9,3]
LENGTH:OUT == 5", 12),
            L(@"LET CUT AS 3
LET LIM AS 5
LIST OUT
PUSH OUT IS 9
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < CUT
      INJECT OUT IS I
      SUM IS SUM + I
   ELIF I == CUT
      PUSH OUT IS I
      SUM IS SUM + CUT
   ELSE
      INJECT OUT IS CUT
      SUM IS SUM + CUT
LET HEAD AS FIRST:OUT
LET TAIL AS LAST:OUT
SUM IS SUM + HEAD
SUM IS SUM + TAIL", @"CUT == 4
SUM >= 22
HEAD <= 4
TAIL != 5
I > CUT
OUT == [4,3,2,1,9,4]
LENGTH:OUT >= 5", 0),
            L(@"LET CUT AS 2
LET LIM AS 6
LIST OUT
PUSH OUT IS 9
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < CUT
      INJECT OUT IS I
      SUM IS SUM + I
   ELIF I == CUT
      PUSH OUT IS I
      SUM IS SUM + CUT
   ELSE
      INJECT OUT IS CUT
      SUM IS SUM + CUT
LET HEAD AS FIRST:OUT
LET TAIL AS LAST:OUT
SUM IS SUM + HEAD
SUM IS SUM + TAIL", @"CUT == 3
SUM <= 21
HEAD != 4
TAIL >= CUT
I >= 6
OUT == [3,3,3,2,1,9,3]
LENGTH:OUT == 7", 0),
            L(@"LET CUT AS 3
LET LIM AS 4
LIST OUT
PUSH OUT IS 9
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < CUT
      INJECT OUT IS I
      SUM IS SUM + I
   ELIF I == CUT
      PUSH OUT IS I
      SUM IS SUM + CUT
   ELSE
      INJECT OUT IS CUT
      SUM IS SUM + CUT
LET HEAD AS FIRST:OUT
LET TAIL AS LAST:OUT
SUM IS SUM + HEAD
SUM IS SUM + TAIL", @"CUT == 4
SUM != 18
TAIL >= CUT
I >= 4
HEAD <= 3
OUT == [3,2,1,9,4]
LENGTH:OUT >= 4
LIM > HEAD", 0),
            L(@"LET CUT AS 2
LET LIM AS 5
LIST OUT
PUSH OUT IS 9
LET I AS 0
LET SUM AS 0
LOOP I < LIM
   I IS I + 1
   IF I < CUT
      INJECT OUT IS I
      SUM IS SUM + I
   ELIF I == CUT
      PUSH OUT IS I
      SUM IS SUM + CUT
   ELSE
      INJECT OUT IS CUT
      SUM IS SUM + CUT
LET HEAD AS FIRST:OUT
LET TAIL AS LAST:OUT
SUM IS SUM + HEAD
SUM IS SUM + TAIL", @"CUT == 3
SUM > CUT
HEAD >= 3
TAIL <= 3
I != 6
OUT == [3,3,2,1,9,3]
LENGTH:OUT == 6
LIM <= 6", 12, 1),

            // Level 19 - list filtering
            L(@"LET CUT AS 4
LIST SRC
PUSH SRC IS 1
PUSH SRC IS 4
PUSH SRC IS 7
PUSH SRC IS 2
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LOOP LENGTH:SRC > 0
   VAL IS SHIFT:SRC
   IF VAL < CUT
      CNT IS CNT + 1
   ELIF VAL == CUT
      PUSH OUT IS VAL
      SUM IS SUM + VAL
   ELSE
      INJECT OUT IS VAL
      SUM IS SUM + VAL
WAIT", @"CUT == 3
VAL >= 2
SUM <= 11
CNT != 3
OUT == [7,4,0]
LENGTH:OUT >= 2
LENGTH:SRC == 0", 12),
            L(@"LET CUT AS 5
LIST SRC
PUSH SRC IS 2
PUSH SRC IS 5
PUSH SRC IS 8
PUSH SRC IS 3
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LOOP LENGTH:SRC > 0
   VAL IS SHIFT:SRC
   IF VAL < CUT
      CNT IS CNT + 1
   ELIF VAL == CUT
      PUSH OUT IS VAL
      SUM IS SUM + VAL
   ELSE
      INJECT OUT IS VAL
      SUM IS SUM + VAL
WAIT", @"CUT == 4
VAL <= 3
SUM != 14
CNT < CUT
OUT == [8,5,0]
LENGTH:OUT == 3
LENGTH:SRC >= 0", 0),
            L(@"LET CUT AS 4
LIST SRC
PUSH SRC IS 1
PUSH SRC IS 4
PUSH SRC IS 9
PUSH SRC IS 2
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LOOP LENGTH:SRC > 0
   VAL IS SHIFT:SRC
   IF VAL < CUT
      CNT IS CNT + 1
   ELIF VAL == CUT
      PUSH OUT IS VAL
      SUM IS SUM + VAL
   ELSE
      INJECT OUT IS VAL
      SUM IS SUM + VAL
WAIT", @"CUT == 3
VAL != 3
SUM > CUT
CNT >= 2
OUT == [9,4,0]
LENGTH:OUT >= 2
LENGTH:SRC == 0", 0),
            L(@"LET CUT AS 5
LIST SRC
PUSH SRC IS 2
PUSH SRC IS 5
PUSH SRC IS 10
PUSH SRC IS 3
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LOOP LENGTH:SRC > 0
   VAL IS SHIFT:SRC
   IF VAL < CUT
      CNT IS CNT + 1
   ELIF VAL == CUT
      PUSH OUT IS VAL
      SUM IS SUM + VAL
   ELSE
      INJECT OUT IS VAL
      SUM IS SUM + VAL
WAIT", @"CUT == 4
VAL < CUT
SUM >= 15
CNT <= 2
OUT == [10,5,0]
LENGTH:OUT == 3
LENGTH:SRC >= 0", 0),
            L(@"LET CUT AS 4
LIST SRC
PUSH SRC IS 1
PUSH SRC IS 4
PUSH SRC IS 11
PUSH SRC IS 2
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LOOP LENGTH:SRC > 0
   VAL IS SHIFT:SRC
   IF VAL < CUT
      CNT IS CNT + 1
   ELIF VAL == CUT
      PUSH OUT IS VAL
      SUM IS SUM + VAL
   ELSE
      INJECT OUT IS VAL
      SUM IS SUM + VAL
WAIT", @"CUT == 3
VAL >= 2
SUM <= 15
CNT != 3
OUT == [11,4,0]
LENGTH:OUT >= 2
LENGTH:SRC == 0", 12, 1),

            // Level 20 - map / reduce
            L(@"LET RATE AS 2
LIST SRC
PUSH SRC IS 1
PUSH SRC IS 2
PUSH SRC IS 3
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET SUM AS 0
LOOP LENGTH:SRC > 0
   VAL IS SHIFT:SRC
   IF VAL < RATE
      VAL IS VAL + RATE
   ELIF VAL == RATE
      VAL IS VAL * RATE
   ELSE
      VAL IS VAL + 1
   PUSH OUT IS VAL
   SUM IS SUM + VAL
WAIT", @"RATE == 3
VAL <= 9
SUM != 19
OUT == [0,4,5,9]
LENGTH:OUT == 4
LENGTH:SRC >= 0", 12),
            L(@"LET RATE AS 3
LIST SRC
PUSH SRC IS 2
PUSH SRC IS 3
PUSH SRC IS 4
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET SUM AS 0
LOOP LENGTH:SRC > 0
   VAL IS SHIFT:SRC
   IF VAL < RATE
      VAL IS VAL + RATE
   ELIF VAL == RATE
      VAL IS VAL * RATE
   ELSE
      VAL IS VAL + 1
   PUSH OUT IS VAL
   SUM IS SUM + VAL
WAIT", @"RATE == 4
VAL != 17
SUM > RATE
OUT == [0,6,7,16]
LENGTH:OUT >= 3
LENGTH:SRC == 0", 0),
            L(@"LET RATE AS 2
LIST SRC
PUSH SRC IS 3
PUSH SRC IS 4
PUSH SRC IS 5
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET SUM AS 0
LOOP LENGTH:SRC > 0
   VAL IS SHIFT:SRC
   IF VAL < RATE
      VAL IS VAL + RATE
   ELIF VAL == RATE
      VAL IS VAL * RATE
   ELSE
      VAL IS VAL + 1
   PUSH OUT IS VAL
   SUM IS SUM + VAL
WAIT", @"RATE == 3
SUM > RATE
VAL >= 6
OUT == [0,9,5,6]
LENGTH:OUT == 4
LENGTH:SRC >= 0", 0),
            L(@"LET RATE AS 3
LIST SRC
PUSH SRC IS 4
PUSH SRC IS 5
PUSH SRC IS 6
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET SUM AS 0
LOOP LENGTH:SRC > 0
   VAL IS SHIFT:SRC
   IF VAL < RATE
      VAL IS VAL + RATE
   ELIF VAL == RATE
      VAL IS VAL * RATE
   ELSE
      VAL IS VAL + 1
   PUSH OUT IS VAL
   SUM IS SUM + VAL
WAIT", @"RATE == 4
SUM >= 29
VAL <= 7
OUT == [0,16,6,7]
LENGTH:OUT >= 3
LENGTH:SRC == 0", 0),
            L(@"LET RATE AS 2
LIST SRC
PUSH SRC IS 5
PUSH SRC IS 6
PUSH SRC IS 7
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET SUM AS 0
LOOP LENGTH:SRC > 0
   VAL IS SHIFT:SRC
   IF VAL < RATE
      VAL IS VAL + RATE
   ELIF VAL == RATE
      VAL IS VAL * RATE
   ELSE
      VAL IS VAL + 1
   PUSH OUT IS VAL
   SUM IS SUM + VAL
WAIT", @"RATE == 3
VAL <= 8
SUM != 22
LENGTH:SRC == 0
LENGTH:OUT >= 3", 12, 1),

            // Level 21 - retry queues
            L(@"LET CUT AS 5
LIST QUE
PUSH QUE IS 1
PUSH QUE IS 6
PUSH QUE IS 2
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET RET AS 0
LOOP LENGTH:QUE > 0
   VAL IS SHIFT:QUE
   IF VAL < CUT
      RET IS RET + 1
      INJECT QUE IS VAL + CUT
      SKIP
   ELIF VAL == CUT
      PUSH DONE IS VAL
   ELSE
      PUSH DONE IS VAL
WAIT", @"CUT == 6
VAL != 9
RET < CUT
DONE == [0,7,6,8]
LENGTH:DONE >= 3
LENGTH:QUE == 0", 12),
            L(@"LET CUT AS 6
LIST QUE
PUSH QUE IS 2
PUSH QUE IS 7
PUSH QUE IS 3
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET RET AS 0
LOOP LENGTH:QUE > 0
   VAL IS SHIFT:QUE
   IF VAL < CUT
      RET IS RET + 1
      INJECT QUE IS VAL + CUT
      SKIP
   ELIF VAL == CUT
      PUSH DONE IS VAL
   ELSE
      PUSH DONE IS VAL
WAIT", @"CUT == 7
VAL > CUT
RET >= 2
DONE == [0,9,7,10]
LENGTH:DONE == 4
LENGTH:QUE >= 0", 0),
            L(@"LET CUT AS 5
LIST QUE
PUSH QUE IS 1
PUSH QUE IS 8
PUSH QUE IS 2
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET RET AS 0
LOOP LENGTH:QUE > 0
   VAL IS SHIFT:QUE
   IF VAL < CUT
      RET IS RET + 1
      INJECT QUE IS VAL + CUT
      SKIP
   ELIF VAL == CUT
      PUSH DONE IS VAL
   ELSE
      PUSH DONE IS VAL
WAIT", @"CUT == 6
VAL >= 8
RET <= 2
DONE == [0,7,8,8]
LENGTH:DONE >= 3
LENGTH:QUE == 0", 0),
            L(@"LET CUT AS 6
LIST QUE
PUSH QUE IS 2
PUSH QUE IS 9
PUSH QUE IS 3
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET RET AS 0
LOOP LENGTH:QUE > 0
   VAL IS SHIFT:QUE
   IF VAL < CUT
      RET IS RET + 1
      INJECT QUE IS VAL + CUT
      SKIP
   ELIF VAL == CUT
      PUSH DONE IS VAL
   ELSE
      PUSH DONE IS VAL
WAIT", @"CUT == 7
VAL <= 10
RET != 3
DONE == [0,9,9,10]
LENGTH:DONE == 4
LENGTH:QUE >= 0", 0),
            L(@"LET CUT AS 5
LIST QUE
PUSH QUE IS 1
PUSH QUE IS 10
PUSH QUE IS 2
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET RET AS 0
LOOP LENGTH:QUE > 0
   VAL IS SHIFT:QUE
   IF VAL < CUT
      RET IS RET + 1
      INJECT QUE IS VAL + CUT
      SKIP
   ELIF VAL == CUT
      PUSH DONE IS VAL
   ELSE
      PUSH DONE IS VAL
WAIT", @"CUT == 6
VAL != 9
RET < CUT
DONE == [0,7,10,8]
LENGTH:DONE >= 3
LENGTH:QUE == 0", 12, 1),

            // Level 22 - stack transforms
            L(@"LET CUT AS 3
LIST STK
PUSH STK IS 1
PUSH STK IS 3
PUSH STK IS 5
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET SUM AS 0
LOOP LENGTH:STK > 0
   VAL IS POP:STK
   IF VAL < CUT
      INJECT OUT IS VAL
   ELIF VAL == CUT
      PUSH OUT IS VAL
   ELSE
      PUSH OUT IS VAL
   SUM IS SUM + VAL
WAIT", @"CUT == 4
VAL < CUT
SUM >= 9
OUT == [1,3,0,5]
LENGTH:OUT == 4
LENGTH:STK >= 0", 12),
            L(@"LET CUT AS 4
LIST STK
PUSH STK IS 2
PUSH STK IS 4
PUSH STK IS 6
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET SUM AS 0
LOOP LENGTH:STK > 0
   VAL IS POP:STK
   IF VAL < CUT
      INJECT OUT IS VAL
   ELIF VAL == CUT
      PUSH OUT IS VAL
   ELSE
      PUSH OUT IS VAL
   SUM IS SUM + VAL
WAIT", @"CUT == 5
VAL >= 2
SUM <= 12
OUT == [2,4,0,6]
LENGTH:OUT >= 3
LENGTH:STK == 0", 0),
            L(@"LET CUT AS 5
LIST STK
PUSH STK IS 3
PUSH STK IS 5
PUSH STK IS 7
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET SUM AS 0
LOOP LENGTH:STK > 0
   VAL IS POP:STK
   IF VAL < CUT
      INJECT OUT IS VAL
   ELIF VAL == CUT
      PUSH OUT IS VAL
   ELSE
      PUSH OUT IS VAL
   SUM IS SUM + VAL
WAIT", @"CUT == 6
VAL <= 3
SUM != 16
OUT == [3,5,0,7]
LENGTH:OUT == 4
LENGTH:STK >= 0", 0),
            L(@"LET CUT AS 6
LIST STK
PUSH STK IS 4
PUSH STK IS 6
PUSH STK IS 8
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET SUM AS 0
LOOP LENGTH:STK > 0
   VAL IS POP:STK
   IF VAL < CUT
      INJECT OUT IS VAL
   ELIF VAL == CUT
      PUSH OUT IS VAL
   ELSE
      PUSH OUT IS VAL
   SUM IS SUM + VAL
WAIT", @"CUT == 7
VAL != 5
SUM > CUT
OUT == [4,6,0,8]
LENGTH:OUT >= 3
LENGTH:STK == 0", 0),
            L(@"LET CUT AS 7
LIST STK
PUSH STK IS 5
PUSH STK IS 7
PUSH STK IS 9
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET SUM AS 0
LOOP LENGTH:STK > 0
   VAL IS POP:STK
   IF VAL < CUT
      INJECT OUT IS VAL
   ELIF VAL == CUT
      PUSH OUT IS VAL
   ELSE
      PUSH OUT IS VAL
   SUM IS SUM + VAL
WAIT", @"CUT == 8
VAL < CUT
SUM >= 21
OUT == [5,7,0,9]
LENGTH:OUT == 4
LENGTH:STK >= 0", 12, 1),

            // Level 23 - dual buffers
            L(@"LET CUT AS 4
LIST A
PUSH A IS 1
PUSH A IS 4
PUSH A IS 7
LIST B
PUSH B IS 2
PUSH B IS 5
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET CNT AS 0
LOOP LENGTH:A > 0 OR LENGTH:B > 0
   IF LENGTH:A > 0
      VAL IS SHIFT:A
   ELIF LENGTH:B > 0
      VAL IS SHIFT:B
   ELSE
      VAL IS 0
   IF VAL < CUT
      INJECT OUT IS VAL
   ELSE
      PUSH OUT IS VAL
   CNT IS CNT + 1
WAIT", @"CUT == 5
VAL >= 5
CNT <= 5
OUT == [2,4,1,0,7,5]
LENGTH:OUT >= 5
LENGTH:A == 0
LENGTH:B >= 0", 12),
            L(@"LET CUT AS 5
LIST A
PUSH A IS 2
PUSH A IS 5
PUSH A IS 8
LIST B
PUSH B IS 3
PUSH B IS 6
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET CNT AS 0
LOOP LENGTH:A > 0 OR LENGTH:B > 0
   IF LENGTH:A > 0
      VAL IS SHIFT:A
   ELIF LENGTH:B > 0
      VAL IS SHIFT:B
   ELSE
      VAL IS 0
   IF VAL < CUT
      INJECT OUT IS VAL
   ELSE
      PUSH OUT IS VAL
   CNT IS CNT + 1
WAIT", @"CUT == 6
VAL <= 6
CNT != 6
OUT == [3,5,2,0,8,6]
LENGTH:OUT == 6
LENGTH:A >= 0
LENGTH:B == 0", 0),
            L(@"LET CUT AS 6
LIST A
PUSH A IS 3
PUSH A IS 6
PUSH A IS 9
LIST B
PUSH B IS 4
PUSH B IS 7
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET CNT AS 0
LOOP LENGTH:A > 0 OR LENGTH:B > 0
   IF LENGTH:A > 0
      VAL IS SHIFT:A
   ELIF LENGTH:B > 0
      VAL IS SHIFT:B
   ELSE
      VAL IS 0
   IF VAL < CUT
      INJECT OUT IS VAL
   ELSE
      PUSH OUT IS VAL
   CNT IS CNT + 1
WAIT", @"CUT == 7
VAL != 8
CNT < CUT
OUT == [4,6,3,0,9,7]
LENGTH:OUT >= 5
LENGTH:A == 0
LENGTH:B >= 0", 0),
            L(@"LET CUT AS 7
LIST A
PUSH A IS 4
PUSH A IS 7
PUSH A IS 10
LIST B
PUSH B IS 5
PUSH B IS 8
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET CNT AS 0
LOOP LENGTH:A > 0 OR LENGTH:B > 0
   IF LENGTH:A > 0
      VAL IS SHIFT:A
   ELIF LENGTH:B > 0
      VAL IS SHIFT:B
   ELSE
      VAL IS 0
   IF VAL < CUT
      INJECT OUT IS VAL
   ELSE
      PUSH OUT IS VAL
   CNT IS CNT + 1
WAIT", @"CUT == 8
VAL >= CUT
CNT >= 5
OUT == [5,7,4,0,10,8]
LENGTH:OUT == 6
LENGTH:A >= 0
LENGTH:B == 0", 0),
            L(@"LET CUT AS 8
LIST A
PUSH A IS 5
PUSH A IS 8
PUSH A IS 11
LIST B
PUSH B IS 6
PUSH B IS 9
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET CNT AS 0
LOOP LENGTH:A > 0 OR LENGTH:B > 0
   IF LENGTH:A > 0
      VAL IS SHIFT:A
   ELIF LENGTH:B > 0
      VAL IS SHIFT:B
   ELSE
      VAL IS 0
   IF VAL < CUT
      INJECT OUT IS VAL
   ELSE
      PUSH OUT IS VAL
   CNT IS CNT + 1
WAIT", @"CUT == 9
VAL >= 9
CNT <= 5
OUT == [6,8,5,0,11,9]
LENGTH:OUT >= 5
LENGTH:A == 0
LENGTH:B >= 0", 12, 1),

            // Level 24 - threshold routing
            L(@"LET LOW AS 5
LET HIGH AS 9
LIST SRC
PUSH SRC IS 2
PUSH SRC IS 6
PUSH SRC IS 10
PUSH SRC IS 4
LIST A
LIST B
LIST C
INJECT A IS 0
LET VAL AS 0
LET CNT AS 0
LOOP LENGTH:SRC > 0
   VAL IS SHIFT:SRC
   IF VAL < LOW
      INJECT A IS VAL
   ELIF VAL < HIGH
      PUSH B IS VAL
   ELSE
      PUSH C IS VAL
   CNT IS CNT + 1
WAIT", @"HIGH == 10
VAL <= 4
CNT != 5
LENGTH:SRC == 0
LENGTH:A >= 2
LENGTH:B == 1
LENGTH:C >= 0", 13),
            L(@"LET LOW AS 6
LET HIGH AS 10
LIST SRC
PUSH SRC IS 3
PUSH SRC IS 7
PUSH SRC IS 11
PUSH SRC IS 5
LIST A
LIST B
LIST C
INJECT A IS 0
LET VAL AS 0
LET CNT AS 0
LOOP LENGTH:SRC > 0
   VAL IS SHIFT:SRC
   IF VAL < LOW
      INJECT A IS VAL
   ELIF VAL < HIGH
      PUSH B IS VAL
   ELSE
      PUSH C IS VAL
   CNT IS CNT + 1
WAIT", @"HIGH == 11
VAL != 6
CNT < HIGH
LENGTH:SRC >= 0
LENGTH:A == 3
LENGTH:B >= 0
LENGTH:C == 1", 0),
            L(@"LET LOW AS 5
LET HIGH AS 9
LIST SRC
PUSH SRC IS 2
PUSH SRC IS 6
PUSH SRC IS 12
PUSH SRC IS 4
LIST A
LIST B
LIST C
INJECT A IS 0
LET VAL AS 0
LET CNT AS 0
LOOP LENGTH:SRC > 0
   VAL IS SHIFT:SRC
   IF VAL < LOW
      INJECT A IS VAL
   ELIF VAL < HIGH
      PUSH B IS VAL
   ELSE
      PUSH C IS VAL
   CNT IS CNT + 1
WAIT", @"HIGH == 10
VAL < HIGH
CNT >= 4
LENGTH:SRC == 0
LENGTH:A >= 2
LENGTH:B == 1
LENGTH:C >= 0
LOW < HIGH", 0),
            L(@"LET LOW AS 6
LET HIGH AS 10
LIST SRC
PUSH SRC IS 3
PUSH SRC IS 7
PUSH SRC IS 13
PUSH SRC IS 5
LIST A
LIST B
LIST C
INJECT A IS 0
LET VAL AS 0
LET CNT AS 0
LOOP LENGTH:SRC > 0
   VAL IS SHIFT:SRC
   IF VAL < LOW
      INJECT A IS VAL
   ELIF VAL < HIGH
      PUSH B IS VAL
   ELSE
      PUSH C IS VAL
   CNT IS CNT + 1
WAIT", @"HIGH == 11
VAL >= 5
CNT <= 4
LENGTH:SRC >= 0
LENGTH:A == 3
LENGTH:B >= 0
LENGTH:C == 1
LOW > VAL", 0),
            L(@"LET LOW AS 5
LET HIGH AS 9
LIST SRC
PUSH SRC IS 2
PUSH SRC IS 6
PUSH SRC IS 14
PUSH SRC IS 4
LIST A
LIST B
LIST C
INJECT A IS 0
LET VAL AS 0
LET CNT AS 0
LOOP LENGTH:SRC > 0
   VAL IS SHIFT:SRC
   IF VAL < LOW
      INJECT A IS VAL
   ELIF VAL < HIGH
      PUSH B IS VAL
   ELSE
      PUSH C IS VAL
   CNT IS CNT + 1
WAIT", @"HIGH == 10
VAL <= 4
CNT != 5
LENGTH:SRC == 0
LENGTH:A >= 2
LENGTH:B == 1
LENGTH:C >= 0
LOW <= 6", 13, 1),

            // Level 25 - bounded retries
            L(@"LET CUT AS 5
LET LIM AS 2
LIST QUE
PUSH QUE IS 1
PUSH QUE IS 6
PUSH QUE IS 2
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET RET AS 0
LOOP LENGTH:QUE > 0
   VAL IS SHIFT:QUE
   IF VAL < CUT
      RET IS RET + 1
      INJECT QUE IS VAL + CUT
      IF RET >= LIM
         STOP
      ELSE
         SKIP
   ELIF VAL == CUT
      PUSH DONE IS VAL
   ELSE
      PUSH DONE IS VAL
WAIT", @"LIM == 3
VAL != 8
RET < LIM
LENGTH:QUE >= 0
LENGTH:DONE == 4
CUT <= 6", 13),
            L(@"LET CUT AS 6
LET LIM AS 3
LIST QUE
PUSH QUE IS 2
PUSH QUE IS 7
PUSH QUE IS 3
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET RET AS 0
LOOP LENGTH:QUE > 0
   VAL IS SHIFT:QUE
   IF VAL < CUT
      RET IS RET + 1
      INJECT QUE IS VAL + CUT
      IF RET >= LIM
         STOP
      ELSE
         SKIP
   ELIF VAL == CUT
      PUSH DONE IS VAL
   ELSE
      PUSH DONE IS VAL
WAIT", @"LIM == 4
VAL > LIM
RET >= 2
LENGTH:QUE == 0
LENGTH:DONE >= 3
CUT >= 5", 0),
            L(@"LET CUT AS 5
LET LIM AS 2
LIST QUE
PUSH QUE IS 1
PUSH QUE IS 8
PUSH QUE IS 2
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET RET AS 0
LOOP LENGTH:QUE > 0
   VAL IS SHIFT:QUE
   IF VAL < CUT
      RET IS RET + 1
      INJECT QUE IS VAL + CUT
      IF RET >= LIM
         STOP
      ELSE
         SKIP
   ELIF VAL == CUT
      PUSH DONE IS VAL
   ELSE
      PUSH DONE IS VAL
WAIT", @"LIM == 3
VAL >= 7
RET <= 2
LENGTH:QUE >= 0
LENGTH:DONE == 4
CUT != 6", 0),
            L(@"LET CUT AS 6
LET LIM AS 3
LIST QUE
PUSH QUE IS 2
PUSH QUE IS 9
PUSH QUE IS 3
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET RET AS 0
LOOP LENGTH:QUE > 0
   VAL IS SHIFT:QUE
   IF VAL < CUT
      RET IS RET + 1
      INJECT QUE IS VAL + CUT
      IF RET >= LIM
         STOP
      ELSE
         SKIP
   ELIF VAL == CUT
      PUSH DONE IS VAL
   ELSE
      PUSH DONE IS VAL
WAIT", @"LIM == 4
VAL <= 9
RET != 3
LENGTH:QUE == 0
LENGTH:DONE >= 3
CUT > LIM", 0),
            L(@"LET CUT AS 5
LET LIM AS 2
LIST QUE
PUSH QUE IS 1
PUSH QUE IS 10
PUSH QUE IS 2
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET RET AS 0
LOOP LENGTH:QUE > 0
   VAL IS SHIFT:QUE
   IF VAL < CUT
      RET IS RET + 1
      INJECT QUE IS VAL + CUT
      IF RET >= LIM
         STOP
      ELSE
         SKIP
   ELIF VAL == CUT
      PUSH DONE IS VAL
   ELSE
      PUSH DONE IS VAL
WAIT", @"LIM == 3
VAL != 8
RET < LIM
LENGTH:QUE >= 0
LENGTH:DONE == 4
CUT > RET", 13, 1),

            // Level 26 - aggregation
            L(@"LET CUT AS 5
LIST DATA
PUSH DATA IS 2
PUSH DATA IS 5
PUSH DATA IS 8
PUSH DATA IS 3
LIST LOW
LIST HIGH
INJECT LOW IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LET MAX AS 0
LOOP LENGTH:DATA > 0
   VAL IS SHIFT:DATA
   SUM IS SUM + VAL
   CNT IS CNT + 1
   IF VAL < CUT
      INJECT LOW IS VAL
   ELIF VAL > MAX
      PUSH HIGH IS VAL
      MAX IS VAL
   ELSE
      PUSH HIGH IS VAL
WAIT", @"CUT == 6
VAL < CUT
SUM >= 18
CNT <= 4
MAX != 9
LOW == [3,5,2,0]
LENGTH:LOW == 4
LENGTH:HIGH >= 0
LENGTH:DATA == 0", 12),
            L(@"LET CUT AS 6
LIST DATA
PUSH DATA IS 3
PUSH DATA IS 6
PUSH DATA IS 9
PUSH DATA IS 4
LIST LOW
LIST HIGH
INJECT LOW IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LET MAX AS 0
LOOP LENGTH:DATA > 0
   VAL IS SHIFT:DATA
   SUM IS SUM + VAL
   CNT IS CNT + 1
   IF VAL < CUT
      INJECT LOW IS VAL
   ELIF VAL > MAX
      PUSH HIGH IS VAL
      MAX IS VAL
   ELSE
      PUSH HIGH IS VAL
WAIT", @"CUT == 7
VAL >= 4
SUM <= 22
CNT != 5
MAX > CUT
LOW == [4,6,3,0]
LENGTH:LOW >= 3
LENGTH:HIGH == 1
LENGTH:DATA >= 0", 0),
            L(@"LET CUT AS 7
LIST DATA
PUSH DATA IS 4
PUSH DATA IS 7
PUSH DATA IS 10
PUSH DATA IS 5
LIST LOW
LIST HIGH
INJECT LOW IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LET MAX AS 0
LOOP LENGTH:DATA > 0
   VAL IS SHIFT:DATA
   SUM IS SUM + VAL
   CNT IS CNT + 1
   IF VAL < CUT
      INJECT LOW IS VAL
   ELIF VAL > MAX
      PUSH HIGH IS VAL
      MAX IS VAL
   ELSE
      PUSH HIGH IS VAL
WAIT", @"CUT == 8
VAL <= 5
SUM != 27
CNT < CUT
MAX >= 10
LOW == [5,7,4,0]
LENGTH:LOW == 4
LENGTH:HIGH >= 0
LENGTH:DATA == 0", 0),
            L(@"LET CUT AS 8
LIST DATA
PUSH DATA IS 5
PUSH DATA IS 8
PUSH DATA IS 11
PUSH DATA IS 6
LIST LOW
LIST HIGH
INJECT LOW IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LET MAX AS 0
LOOP LENGTH:DATA > 0
   VAL IS SHIFT:DATA
   SUM IS SUM + VAL
   CNT IS CNT + 1
   IF VAL < CUT
      INJECT LOW IS VAL
   ELIF VAL > MAX
      PUSH HIGH IS VAL
      MAX IS VAL
   ELSE
      PUSH HIGH IS VAL
WAIT", @"CUT == 9
VAL != 7
SUM > CUT
CNT >= 4
MAX <= 11
LOW == [6,8,5,0]
LENGTH:LOW >= 3
LENGTH:HIGH == 1
LENGTH:DATA >= 0", 0),
            L(@"LET CUT AS 9
LIST DATA
PUSH DATA IS 6
PUSH DATA IS 9
PUSH DATA IS 12
PUSH DATA IS 7
LIST LOW
LIST HIGH
INJECT LOW IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LET MAX AS 0
LOOP LENGTH:DATA > 0
   VAL IS SHIFT:DATA
   SUM IS SUM + VAL
   CNT IS CNT + 1
   IF VAL < CUT
      INJECT LOW IS VAL
   ELIF VAL > MAX
      PUSH HIGH IS VAL
      MAX IS VAL
   ELSE
      PUSH HIGH IS VAL
WAIT", @"CUT == 10
VAL < CUT
SUM >= 34
CNT <= 4
MAX != 13
LOW == [7,9,6,0]
LENGTH:LOW == 4
LENGTH:HIGH >= 0
LENGTH:DATA == 0", 12, 1),

            // Level 27 - ordered merging
            L(@"LET CUT AS 6
LIST A
PUSH A IS 1
PUSH A IS 4
PUSH A IS 7
LIST B
PUSH B IS 2
PUSH B IS 5
PUSH B IS 8
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET CNT AS 0
LOOP LENGTH:A > 0 OR LENGTH:B > 0
   IF LENGTH:A > 0
      VAL IS SHIFT:A
   ELIF LENGTH:B > 0
      VAL IS SHIFT:B
   ELSE
      VAL IS 0
   IF VAL < CUT
      PUSH OUT IS VAL
   ELSE
      INJECT OUT IS VAL
   CNT IS CNT + 1
WAIT", @"CUT == 7
VAL >= 8
CNT <= 6
LENGTH:A >= 0
LENGTH:B == 0
LENGTH:OUT >= 6", 12),
            L(@"LET CUT AS 7
LIST A
PUSH A IS 2
PUSH A IS 5
PUSH A IS 8
LIST B
PUSH B IS 3
PUSH B IS 6
PUSH B IS 9
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET CNT AS 0
LOOP LENGTH:A > 0 OR LENGTH:B > 0
   IF LENGTH:A > 0
      VAL IS SHIFT:A
   ELIF LENGTH:B > 0
      VAL IS SHIFT:B
   ELSE
      VAL IS 0
   IF VAL < CUT
      PUSH OUT IS VAL
   ELSE
      INJECT OUT IS VAL
   CNT IS CNT + 1
WAIT", @"CUT == 8
VAL <= 9
CNT != 7
LENGTH:A == 0
LENGTH:B >= 0
LENGTH:OUT == 7", 0),
            L(@"LET CUT AS 8
LIST A
PUSH A IS 3
PUSH A IS 6
PUSH A IS 9
LIST B
PUSH B IS 4
PUSH B IS 7
PUSH B IS 10
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET CNT AS 0
LOOP LENGTH:A > 0 OR LENGTH:B > 0
   IF LENGTH:A > 0
      VAL IS SHIFT:A
   ELIF LENGTH:B > 0
      VAL IS SHIFT:B
   ELSE
      VAL IS 0
   IF VAL < CUT
      PUSH OUT IS VAL
   ELSE
      INJECT OUT IS VAL
   CNT IS CNT + 1
WAIT", @"CUT == 9
VAL != 11
CNT < CUT
LENGTH:A >= 0
LENGTH:B == 0
LENGTH:OUT >= 6", 0),
            L(@"LET CUT AS 9
LIST A
PUSH A IS 4
PUSH A IS 7
PUSH A IS 10
LIST B
PUSH B IS 5
PUSH B IS 8
PUSH B IS 11
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET CNT AS 0
LOOP LENGTH:A > 0 OR LENGTH:B > 0
   IF LENGTH:A > 0
      VAL IS SHIFT:A
   ELIF LENGTH:B > 0
      VAL IS SHIFT:B
   ELSE
      VAL IS 0
   IF VAL < CUT
      PUSH OUT IS VAL
   ELSE
      INJECT OUT IS VAL
   CNT IS CNT + 1
WAIT", @"CUT == 10
VAL > CUT
CNT >= 6
LENGTH:A == 0
LENGTH:B >= 0
LENGTH:OUT == 7", 0),
            L(@"LET CUT AS 10
LIST A
PUSH A IS 5
PUSH A IS 8
PUSH A IS 11
LIST B
PUSH B IS 6
PUSH B IS 9
PUSH B IS 12
LIST OUT
INJECT OUT IS 0
LET VAL AS 0
LET CNT AS 0
LOOP LENGTH:A > 0 OR LENGTH:B > 0
   IF LENGTH:A > 0
      VAL IS SHIFT:A
   ELIF LENGTH:B > 0
      VAL IS SHIFT:B
   ELSE
      VAL IS 0
   IF VAL < CUT
      PUSH OUT IS VAL
   ELSE
      INJECT OUT IS VAL
   CNT IS CNT + 1
WAIT", @"CUT == 11
VAL >= 12
CNT <= 6
LENGTH:A >= 0
LENGTH:B == 0
LENGTH:OUT >= 6", 12, 1),

            // Level 28 - priority scheduler
            L(@"LET CUT AS 7
LIST NORM
PUSH NORM IS 3
PUSH NORM IS 6
PUSH NORM IS 9
LIST PRIO
INJECT PRIO IS 1
INJECT PRIO IS 2
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET PCNT AS 0
LOOP LENGTH:NORM > 0 OR LENGTH:PRIO > 0
   IF LENGTH:PRIO > 0
      VAL IS SHIFT:PRIO
      PCNT IS PCNT + 1
   ELIF LENGTH:NORM > 0
      VAL IS SHIFT:NORM
   ELSE
      VAL IS 0
   IF VAL < CUT
      PUSH DONE IS VAL
   ELSE
      INJECT DONE IS VAL
WAIT", @"CUT == 8
VAL <= 9
PCNT != 3
LENGTH:NORM == 0
LENGTH:PRIO >= 0
LENGTH:DONE == 6", 12),
            L(@"LET CUT AS 8
LIST NORM
PUSH NORM IS 4
PUSH NORM IS 7
PUSH NORM IS 10
LIST PRIO
INJECT PRIO IS 2
INJECT PRIO IS 3
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET PCNT AS 0
LOOP LENGTH:NORM > 0 OR LENGTH:PRIO > 0
   IF LENGTH:PRIO > 0
      VAL IS SHIFT:PRIO
      PCNT IS PCNT + 1
   ELIF LENGTH:NORM > 0
      VAL IS SHIFT:NORM
   ELSE
      VAL IS 0
   IF VAL < CUT
      PUSH DONE IS VAL
   ELSE
      INJECT DONE IS VAL
WAIT", @"CUT == 9
VAL != 11
PCNT < CUT
LENGTH:NORM >= 0
LENGTH:PRIO == 0
LENGTH:DONE >= 5", 0),
            L(@"LET CUT AS 9
LIST NORM
PUSH NORM IS 5
PUSH NORM IS 8
PUSH NORM IS 11
LIST PRIO
INJECT PRIO IS 3
INJECT PRIO IS 4
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET PCNT AS 0
LOOP LENGTH:NORM > 0 OR LENGTH:PRIO > 0
   IF LENGTH:PRIO > 0
      VAL IS SHIFT:PRIO
      PCNT IS PCNT + 1
   ELIF LENGTH:NORM > 0
      VAL IS SHIFT:NORM
   ELSE
      VAL IS 0
   IF VAL < CUT
      PUSH DONE IS VAL
   ELSE
      INJECT DONE IS VAL
WAIT", @"CUT == 10
VAL > CUT
PCNT >= 2
LENGTH:NORM == 0
LENGTH:PRIO >= 0
LENGTH:DONE == 6", 0),
            L(@"LET CUT AS 10
LIST NORM
PUSH NORM IS 6
PUSH NORM IS 9
PUSH NORM IS 12
LIST PRIO
INJECT PRIO IS 4
INJECT PRIO IS 5
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET PCNT AS 0
LOOP LENGTH:NORM > 0 OR LENGTH:PRIO > 0
   IF LENGTH:PRIO > 0
      VAL IS SHIFT:PRIO
      PCNT IS PCNT + 1
   ELIF LENGTH:NORM > 0
      VAL IS SHIFT:NORM
   ELSE
      VAL IS 0
   IF VAL < CUT
      PUSH DONE IS VAL
   ELSE
      INJECT DONE IS VAL
WAIT", @"CUT == 11
VAL >= 12
PCNT <= 2
LENGTH:NORM >= 0
LENGTH:PRIO == 0
LENGTH:DONE >= 5", 0),
            L(@"LET CUT AS 11
LIST NORM
PUSH NORM IS 7
PUSH NORM IS 10
PUSH NORM IS 13
LIST PRIO
INJECT PRIO IS 5
INJECT PRIO IS 6
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET PCNT AS 0
LOOP LENGTH:NORM > 0 OR LENGTH:PRIO > 0
   IF LENGTH:PRIO > 0
      VAL IS SHIFT:PRIO
      PCNT IS PCNT + 1
   ELIF LENGTH:NORM > 0
      VAL IS SHIFT:NORM
   ELSE
      VAL IS 0
   IF VAL < CUT
      PUSH DONE IS VAL
   ELSE
      INJECT DONE IS VAL
WAIT", @"CUT == 12
VAL <= 13
PCNT != 3
LENGTH:NORM == 0
LENGTH:PRIO >= 0
LENGTH:DONE == 6", 12, 1),

            // Level 29 - sentinels
            L(@"LET CUT AS 5
LIST IN
PUSH IN IS 3
PUSH IN IS 5
PUSH IN IS 0
PUSH IN IS 8
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LOOP LENGTH:IN > 0
   VAL IS SHIFT:IN
   IF VAL == 0
      STOP
   ELIF VAL < CUT
      INJECT DONE IS VAL
      SUM IS SUM + VAL
   ELSE
      PUSH DONE IS VAL
      SUM IS SUM + VAL
   CNT IS CNT + 1
WAIT", @"CUT == 6
VAL != 1
SUM > CUT
CNT >= 2
DONE == [5,3,0]
LENGTH:DONE >= 2
LENGTH:IN == 1", 12),
            L(@"LET CUT AS 6
LIST IN
PUSH IN IS 4
PUSH IN IS 6
PUSH IN IS 0
PUSH IN IS 9
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LOOP LENGTH:IN > 0
   VAL IS SHIFT:IN
   IF VAL == 0
      STOP
   ELIF VAL < CUT
      INJECT DONE IS VAL
      SUM IS SUM + VAL
   ELSE
      PUSH DONE IS VAL
      SUM IS SUM + VAL
   CNT IS CNT + 1
WAIT", @"CUT == 7
VAL < CUT
SUM >= 10
CNT <= 2
DONE == [6,4,0]
LENGTH:DONE == 3
LENGTH:IN >= 0", 0),
            L(@"LET CUT AS 7
LIST IN
PUSH IN IS 5
PUSH IN IS 7
PUSH IN IS 0
PUSH IN IS 10
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LOOP LENGTH:IN > 0
   VAL IS SHIFT:IN
   IF VAL == 0
      STOP
   ELIF VAL < CUT
      INJECT DONE IS VAL
      SUM IS SUM + VAL
   ELSE
      PUSH DONE IS VAL
      SUM IS SUM + VAL
   CNT IS CNT + 1
WAIT", @"CUT == 8
VAL >= 0
SUM <= 12
CNT != 3
DONE == [7,5,0]
LENGTH:DONE >= 2
LENGTH:IN == 1", 0),
            L(@"LET CUT AS 8
LIST IN
PUSH IN IS 6
PUSH IN IS 8
PUSH IN IS 0
PUSH IN IS 11
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LOOP LENGTH:IN > 0
   VAL IS SHIFT:IN
   IF VAL == 0
      STOP
   ELIF VAL < CUT
      INJECT DONE IS VAL
      SUM IS SUM + VAL
   ELSE
      PUSH DONE IS VAL
      SUM IS SUM + VAL
   CNT IS CNT + 1
WAIT", @"CUT == 9
VAL <= 0
SUM != 15
CNT < CUT
DONE == [8,6,0]
LENGTH:DONE == 3
LENGTH:IN >= 0", 0),
            L(@"LET CUT AS 9
LIST IN
PUSH IN IS 7
PUSH IN IS 9
PUSH IN IS 0
PUSH IN IS 12
LIST DONE
INJECT DONE IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LOOP LENGTH:IN > 0
   VAL IS SHIFT:IN
   IF VAL == 0
      STOP
   ELIF VAL < CUT
      INJECT DONE IS VAL
      SUM IS SUM + VAL
   ELSE
      PUSH DONE IS VAL
      SUM IS SUM + VAL
   CNT IS CNT + 1
WAIT", @"CUT == 10
VAL != 1
SUM > CUT
CNT >= 2
DONE == [9,7,0]
LENGTH:DONE >= 2
LENGTH:IN == 1", 12, 1),

            // Level 30 - final dispatch
            L(@"LET CUT AS 5
LIST IN
PUSH IN IS 3
PUSH IN IS 8
PUSH IN IS 1
PUSH IN IS 0
PUSH IN IS 6
LIST GOOD
LIST RET
INJECT RET IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LOOP LENGTH:IN > 0
   VAL IS SHIFT:IN
   IF VAL == 0
      STOP
   ELIF VAL >= CUT
      PUSH GOOD IS VAL
      SUM IS SUM + VAL
   ELSE
      INJECT RET IS VAL + CUT
      CNT IS CNT + 1
WAIT", @"CUT == 6
VAL < CUT
SUM >= 8
CNT <= 2
RET == [7,9,0]
LENGTH:RET == 3
LENGTH:IN >= 0
LENGTH:GOOD == 1", 12),
            L(@"LET CUT AS 6
LIST IN
PUSH IN IS 4
PUSH IN IS 9
PUSH IN IS 2
PUSH IN IS 0
PUSH IN IS 7
LIST GOOD
LIST RET
INJECT RET IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LOOP LENGTH:IN > 0
   VAL IS SHIFT:IN
   IF VAL == 0
      STOP
   ELIF VAL >= CUT
      PUSH GOOD IS VAL
      SUM IS SUM + VAL
   ELSE
      INJECT RET IS VAL + CUT
      CNT IS CNT + 1
WAIT", @"CUT == 7
VAL >= 0
SUM <= 9
CNT != 3
RET == [9,11,0]
LENGTH:RET >= 2
LENGTH:IN == 1
LENGTH:GOOD >= 0", 0),
            L(@"LET CUT AS 5
LIST IN
PUSH IN IS 3
PUSH IN IS 10
PUSH IN IS 3
PUSH IN IS 0
PUSH IN IS 8
LIST GOOD
LIST RET
INJECT RET IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LOOP LENGTH:IN > 0
   VAL IS SHIFT:IN
   IF VAL == 0
      STOP
   ELIF VAL >= CUT
      PUSH GOOD IS VAL
      SUM IS SUM + VAL
   ELSE
      INJECT RET IS VAL + CUT
      CNT IS CNT + 1
WAIT", @"CUT == 6
VAL <= 0
SUM != 11
CNT < CUT
RET == [9,9,0]
LENGTH:RET == 3
LENGTH:IN >= 0
LENGTH:GOOD == 1", 0),
            L(@"LET CUT AS 6
LIST IN
PUSH IN IS 4
PUSH IN IS 11
PUSH IN IS 1
PUSH IN IS 0
PUSH IN IS 9
LIST GOOD
LIST RET
INJECT RET IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LOOP LENGTH:IN > 0
   VAL IS SHIFT:IN
   IF VAL == 0
      STOP
   ELIF VAL >= CUT
      PUSH GOOD IS VAL
      SUM IS SUM + VAL
   ELSE
      INJECT RET IS VAL + CUT
      CNT IS CNT + 1
WAIT", @"CUT == 7
VAL != 1
SUM > CUT
CNT >= 2
RET == [8,11,0]
LENGTH:RET >= 2
LENGTH:IN == 1
LENGTH:GOOD >= 0", 0),
            L(@"LET CUT AS 5
LIST IN
PUSH IN IS 3
PUSH IN IS 12
PUSH IN IS 2
PUSH IN IS 0
PUSH IN IS 10
LIST GOOD
LIST RET
INJECT RET IS 0
LET VAL AS 0
LET SUM AS 0
LET CNT AS 0
LOOP LENGTH:IN > 0
   VAL IS SHIFT:IN
   IF VAL == 0
      STOP
   ELIF VAL >= CUT
      PUSH GOOD IS VAL
      SUM IS SUM + VAL
   ELSE
      INJECT RET IS VAL + CUT
      CNT IS CNT + 1
WAIT", @"CUT == 6
VAL < CUT
SUM >= 12
CNT <= 2
RET == [8,9,0]
LENGTH:RET == 3
LENGTH:IN >= 0
LENGTH:GOOD == 1", 12, 1),

        };
    }
}
